ls:
  src:
    .js: kebab-case | PascalCase
    .json: kebab-case
    .vue: PascalCase
    .ts: camelCase | PascalCase
    .d.ts: camelCase
    .spec.ts: camelCase | PascalCase
    .mock.ts: camelCase
